export const
  PLAYER_WIDTH = 45,
  PLAYER_HEIGHT = 36,
  PLAYER_INITIAL_FRAME = 1,
  PLAYER_SPEED = 500,
  PLAYER_SNEAK_MULTIPLIER = 0.75,
  PLAYER_SPRINT_MULTIPLIER = 1.5,
  PLAYER_WALK_ANIMATION_FRAMERATE = 5;
