export const
  PLAYER_WIDTH = 22.5,
  PLAYER_HEIGHT = 18,
  PLAYER_INITIAL_FRAME = 1,
  PLAYER_SPEED = 150,
  PLAYER_SNEAK_MULTIPLIER = 0.75,
  PLAYER_SPRINT_MULTIPLIER = 1.5,
  PLAYER_WALK_ANIMATION_FRAMERATE = 5;
