export const
  PLAYER_WIDTH = 30,
  PLAYER_HEIGHT = 24,
  PLAYER_INITIAL_FRAME = 1,
  PLAYER_SPEED = 200,
  PLAYER_SNEAK_MULTIPLIER = 0.75,
  PLAYER_SPRINT_MULTIPLIER = 1.5,
  PLAYER_WALK_ANIMATION_FRAMERATE = 5,
  PLAYER_FIGHT_ANIMATION_FRAMERATE = 10;
