export const
  ZOMBIE_WIDTH = 36,
  ZOMBIE_HEIGHT = 36,
  ZOMBIE_INITIAL_FRAME = 1,
  ZOMBIE_SPEED = 100,
  ZOMBIE_SNEAK_MULTIPLIER = 0.75,
  ZOMBIE_SPRINT_MULTIPLIER = 1.5,
  ZOMBIE_WALK_ANIMATION_FRAMERATE = 5,
  ZOMBIE_FIGHT_ANIMATION_FRAMERATE = 10;
